### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by BradCOnGitHub** [FabysGames/mythicplustimer#13]
While doing the hunt in the beastwarrens:

  
  Message: Interface\AddOns\MythicPlusTimer\progress.lua:146: attempt to compare number with nil
  Time: Mon Jan 18 18:40:41 2021
  Count: 9
  Stack: Interface\AddOns\MythicPlusTimer\progress.lua:146: attempt to compare number with nil
  [string "@Interface\AddOns\MythicPlusTimer\progress.lua"]:146: in function `callback'
  [string "@Interface\AddOns\MythicPlusTimer\addon.lua"]:100: in function &lt;Interface\AddOns\MythicPlusTimer\addon.lua:94&gt;
  
  Locals: current_run = &lt;table&gt; {
   is_completed = true
   is_teeming = false
   is_prideful = true
   quantity_number = 500
   cm_level = 13
   elapsed_time = 2941
   deathcount = 36
   quantity_completed = true
   time_left_3 = 0
   zone_name = "Spires of Ascension"
   affixes_key = "affixes-9-6-13-121"
   time_left = 0
   deathcount_visible = true
   steps = 5
   death_names = &lt;table&gt; {
   }
   current_zone_id = 2285
   is_reaping = false
   times = &lt;table&gt; {
   }
   max_time = 2340
   affixes = &lt;table&gt; {
   }
   current_map_id = 381
   pull = &lt;table&gt; {
   }
   level_key = "l13"
   final_quantity_number = 500
   time_left_2 = 0
  }
  _ = "Ritual Experimentation"
  _ = "Defeat Displaced Soul Feeders before they are consumed by the Shifting Life-Eater."
  steps = 1
  _ = "Destroy Displaced Soul Feeders"
  _ = 92
  _ = false
  _ = 9
  final_value = 20
  _ = 0
  _ = 77829
  quantity = "9"
  quantity_number = nil
  (*temporary) = 1
  (*temporary) = ""
  (*temporary) = nil
  (*temporary) = ""
  (*temporary) = 1
  (*temporary) = false
  (*temporary) = nil
  (*temporary) = nil
  (*temporary) = "attempt to compare number with nil"
  main = &lt;table&gt; {
   get_current_run = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:572
   on_player_entering_world = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:496
   enable = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:691
   get_quest_frame = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:592
   show_frame = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:655
   show_default_tracker = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:643
   get_frame = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:582
   init = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:681
   reset_current_run = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:577
   show_demo = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:675
   toggle_frame_movement = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:665
   is_frame_moveable = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:670
   hide_frame = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:660
   name = "main"
   get_info_frames = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:587
   on_challenge_mode_start = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:509
   is_in_cm = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:617
   format_seconds = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:603
   hide_default_tracker = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\main.lua:625
  }
  last_quantity = 1
  last_kill = nil
  update_progress_value = &lt;function&gt; defined @Interface\AddOns\MythicPlusTimer\progress.lua:20

**Comment by fabysdev** [comment]
Should no longer happen with the latest version
