### ISSUE TITLE
Request - right text alignment

### ISSUE THREAD

**Issue by mBlinkii** [FabysGames/mythicplustimer#18]
Hi, is it possible to add an option for the text alignment, I would like the text to be right aligned and have not found an adjustable option.

As an example I have created this image. https://ibb.co/KNTzV3V

**Comment by mBlinkii** [comment]
@fabysdev 

It should be easy to change the orientation of the texts just as an example.  I would also be very happy about this option.

```
 if alignment_right then
    time_left_frame.text:SetPoint("TOPRIGHT", time_left_frame, "LEFT")
  else
    time_left_frame.text:SetPoint("TOPLEFT", time_left_frame, "RIGHT")
  end
```

**Comment by fabysdev** [comment]
Sorry for the late answer, i was not active in WoW.

MythicPlusTimer 4.7.0 has the option for right alignment now.
