### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Melethrion** [FabysGames/mythicplustimer#19]
15x MythicPlusTimer\main.lua:544: attempt to index field '?' (a nil value)
[string "@MythicPlusTimer\main.lua"]:544: in function `on_challenge_mode_complete'
[string "@MythicPlusTimer\criteria.lua"]:502: in function `callback'
[string "@MythicPlusTimer\addon.lua"]:100: in function <MythicPlusTimer\addon.lua:94>

Locals:
current_run = <table> {
 is_completed = true
 is_teeming = false
 is_prideful = true
 quantity_number = "235"
 cm_level = 18
 time_left_3 = 0
 elapsed_time = 1498
 deathcount = 14
 zone_name = "Spitzen des Aufstiegs"
 affixes_key = "affixes-10-8-12-121"
 time_left = 842
 deathcount_visible = true
 steps = 5
 death_names = <table> {
 }
 current_zone_id = 2285
 is_reaping = false
 times = <table> {
 }
 max_time = 2340
 affixes = <table> {
 }
 current_map_id = 381
 pull = <table> {
 }
 level_key = "l18"
 final_quantity_number = 285
 time_left_2 = 374
}
best_runs = <table> {
}
(*temporary) = nil
(*temporary) = "l18affixes-10-8-12-121"
(*temporary) = "affixes-10-8-12-121"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
addon = <table> {
 c = <function> defined @MythicPlusTimer\addon.lua:59
 add_locale = <function> defined @MythicPlusTimer\addon.lua:11
 t = <function> defined @MythicPlusTimer\addon.lua:16
 set_config_value = <function> defined @MythicPlusTimer\addon.lua:42
 print = <function> defined @MythicPlusTimer\addon.lua:138
 new_module = <function> defined @MythicPlusTimer\addon.lua:163
 get_module = <function> defined @MythicPlusTimer\addon.lua:174
 unregister_event = <function> defined @MythicPlusTimer\addon.lua:118
 unregister_config_listener = <function> defined @MythicPlusTimer\addon.lua:73
 register_event = <function> defined @MythicPlusTimer\addon.lua:108
 set_config = <function> defined @MythicPlusTimer\addon.lua:33
 register_config_listener = <function> defined @MythicPlusTimer\addon.lua:64
}

**Comment by fabysdev** [comment]
did this happen in / after a mythic+ or somewhere different? thanks

**Comment by fabysdev** [comment]
this should be fixed in 4.8.1, thanks for the report
