### ISSUE TITLE
Consider hosting add-on here?

### ISSUE THREAD

**Issue by nezorflame** [FabysGames/mythicplustimer#20]
Would you consider hosting the add-on here so those of us who wish to avoid Overwolf could do so?
It'd be nice to have the addon packaged as release ZIPs here to be supported by other package managers (e.g. [CurseBreaker](https://github.com/AcidWeb/CurseBreaker)).
Thank you!

Here's the conversation on another add-ons:
https://github.com/SLOKnightfall/BetterWardrobe/issues/250
https://github.com/davidmeen/TomeOfTeleportation/issues/14

**Comment by fabysdev** [comment]
There are already releases for the addon here on Github containing the zip file
For example https://github.com/FabysGames/mythicplustimer/releases/tag/4.8.0

The addon is also available on wago.io: https://addons.wago.io/addons/mythicplustimer to avoid Overwolf

So I think this is already happening or am I missing something?
