### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eldoggo** [FabysGames/mythicplustimer#25]
Error. Preventing spell casting from actionbar. Happens sometimes after changing zones or open vendors.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'MythicPlusTimer' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR2BUTTON11"]:2: in function <[string "MULTIACTIONBAR2BUTTON11"]:1>

**Comment by fabysdev** [comment]
i was not able to reproduce this, please reopen if you have reproducible steps, thanks
