### ISSUE TITLE
Issue while exploring

### ISSUE THREAD

**Issue by Dagweb** [FabysGames/mythicplustimer#26]
I was doing nothing special, i was walking in Zereth Moris and this error show up.
I hoppe this will help you to make your addon even better.

1x MythicPlusTimer/progress.lua:181: attempt to call method 'GetUnit' (a nil value)
[string "@MythicPlusTimer/progress.lua"]:181: in function <MythicPlusTimer/progress.lua:175>
[string "=(tail call)"]: ?
[string "=[C]"]: in function 'securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function 'SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:908: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:743>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:949: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:925>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:166: in function <HandyNotes/HandyNotes.lua:165>

Locals:
tooltip = HandyNotes_ShadowlandsTreasuresComparisonTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 AllTheThingsOnTooltipClearedHook = true
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLFGDungeonShortageReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 InternalProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:240
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBuybackItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 hasMoney = 1
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 numMoneyFrames = 1
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 info = <table> {
 }
 updateTooltipTimer = 0.200000
 SetLootRollItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = HandyNotes_ShadowlandsTreasuresComparisonTooltipTextRight1 {
 }
 SetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLineDataAttribute = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:232
 SetAchievementByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInventoryItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetCurrencyByID = <function> defined @

**Comment by fabysdev** [comment]
Tooltip issues should be fixed in 5.0.2
