### ISSUE TITLE
FR: keep objective frame hidden while still in dungeon after finishing

### ISSUE THREAD

**Issue by Belatar** [FabysGames/mythicplustimer#29]
hi, i didnt find any comment section on the wago site, so im trying it this way. if you prefer feedback / feature requests via another channel please let me know.

its a minor cosmetic thing: could you please make it so that the objective frame remains hidden even after killing the final boss of the m+ dungeon as long as the character remains in the instance.
i positioned m+timer and the objective frame on top of each other and it looks really crappy after killing the last boss when the objective frame reappears but m+timer is still there.

**Comment by fabysdev** [comment]
the objective frame should stay hidden in the new version 5.2.0
