### ISSUE TITLE
Shows only timers

### ISSUE THREAD

**Issue by spromicky** [FabysGames/mythicplustimer#3]
After 3.0 update sometimes (not often) when keystone starts `mythicplustimer` show only timers and affixes. And not showing objectives, trash percents and reaping counter. Disabling and enabling this in preferences not have any effect.

**Comment by FabysGames** [comment]
thanks, looking at it

**Comment by spromicky** [comment]
reload helps btw

**Comment by FabysGames** [comment]
Please try the latest version, 3.2

**Comment by spromicky** [comment]
All right. Thx for fix!
