### ISSUE TITLE
Shades temporarily count as percent

### ISSUE THREAD

**Issue by hdmark** [FabysGames/mythicplustimer#33]
I'm seeing shades count as 3% ish for the % in the current pull.  Not sure why but then it seems to potentially mess up count afterwards.  In the last pull of Alg, it was showing me at 93.xx and then the last pull should be 6% but the numbers were not adding up until after the kill.

**Comment by fabysdev** [comment]
there was most likely a timing issue while resolving the % an npc gives. (this is done by checking the % change when an npc dies)

in such cases, deleting the progress database schould resolve the issue (MDT is used as backup, so there will always be a % display). you can do this by clicking the button "Delete progress percent database" within the options.
