### ISSUE TITLE
Incorrect bonus chest timers in Neltharus

### ISSUE THREAD

**Issue by Bukama** [FabysGames/mythicplustimer#34]
The timers of Neltharus (new DF instance) are not accurate.

The first dungeon I played with a timer left of +0:58 for +3, but we only got +2.
The second dungeon, we finished +1:36 for +3 and got +3. So the border seems to be somethere between that.

**Comment by fabysdev** [comment]
interesting, i have not seen any change to the timings, should be 80% and 60% as they always were.

I checked multiple sources and they all say (including mythicplustimer) 19:48 for +3 and 26:24 for +2.
do you have any further informations about the times in that dungeon?

![image](https://github.com/FabysGames/mythicplustimer/assets/2088490/561c71cc-ebcc-40d7-9a34-ddc8677ddb10)

**Comment by Bukama** [comment]
I'm afraid I don't have. There's a high chance I'll do some Nel runs today for rating, then I'll keep an eye on it.
