### ISSUE TITLE
attempt to index global 'ScenarioObjectiveTracker' (a nil value)

### ISSUE THREAD

**Issue by R41z0r** [FabysGames/mythicplustimer#38]
Since the new update 5h ago when I log in I immediately getting this error. I also disabled all addons but MythicPlusTimer and the error persists.

```

5x MythicPlusTimer/timer.lua:380: attempt to index global 'ScenarioObjectiveTracker' (a nil value)
[string "@MythicPlusTimer/timer.lua"]:380: in main chunk

Locals:
_ = "MythicPlusTimer"
addon = <table> {
 c = <function> defined @MythicPlusTimer/addon.lua:59
 add_locale = <function> defined @MythicPlusTimer/addon.lua:11
 t = <function> defined @MythicPlusTimer/addon.lua:16
 set_config_value = <function> defined @MythicPlusTimer/addon.lua:42
 print = <function> defined @MythicPlusTimer/addon.lua:138
 new_module = <function> defined @MythicPlusTimer/addon.lua:163
 get_module = <function> defined @MythicPlusTimer/addon.lua:174
 unregister_event = <function> defined @MythicPlusTimer/addon.lua:118
 unregister_config_listener = <function> defined @MythicPlusTimer/addon.lua:73
 register_event = <function> defined @MythicPlusTimer/addon.lua:108
 set_config = <function> defined @MythicPlusTimer/addon.lua:33
 register_config_listener = <function> defined @MythicPlusTimer/addon.lua:64
}
timer = <table> {
 enable = <function> defined @MythicPlusTimer/timer.lua:369
 name = "timer"
 on_player_entering_world = <function> defined @MythicPlusTimer/timer.lua:337
 on_challenge_mode_start = <function> defined @MythicPlusTimer/timer.lua:326
 init = <function> defined @MythicPlusTimer/timer.lua:361
 update_time = <function> defined @MythicPlusTimer/timer.lua:350
 get_time_3_frame = <function> defined @MythicPlusTimer/timer.lua:355
}
main = nil
criteria = nil
infos = nil
timer_frames = <table> {
}
on_frame_mousedown = <function> defined @MythicPlusTimer/timer.lua:13
create_timer_frames = <function> defined @MythicPlusTimer/timer.lua:38
update_frame_points = <function> defined @MythicPlusTimer/timer.lua:147
on_update_time = <function> defined @MythicPlusTimer/timer.lua:173
on_challenge_mode_completed = <function> defined @MythicPlusTimer/timer.lua:316
on_challenge_mode_reset = <function> defined @MythicPlusTimer/timer.lua:321
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ScenarioObjectiveTracker' (a nil value)"
```

**Comment by R41z0r** [comment]
Something like this should be implemented, if the actual 10.X Version is overwritten with WoW11X stuff:
local version = GetBuildInfo()
local majorVersion = tonumber(string.match(version, "(%d+)%."))
if majorVersion >= 11 then
  hooksecurefunc(ScenarioObjectiveTracker.ChallengeModeBlock, "UpdateTime", on_update_time)
else
  hooksecurefunc("Scenario_ChallengeMode_UpdateTime", on_update_time)
end

**Comment by fabysdev** [comment]
the 10.x version ist not overriden. on curseforge and wago only the 11.0 verison is selected, please check your updater, so you  only get the supported version of the addon and not the latest one (which only works for 11.0)

**Comment by zaphon** [comment]
You might want to check with Curseforge than as I'm using their Updater, and the 11.0 version is overwriting the 10.2.0 version (and there is no setting to say only install the 10.2.0 version, just Release, Beta, Alpha), which is why everyone is having issues. I'm manually downgrading.

**Comment by R41z0r** [comment]
> You might want to check with Curseforge than as I'm using their Updater, and the 11.0 version is overwriting the 10.2.0 version (and there is no setting to say only install the 10.2.0 version, just Release, Beta, Alpha), which is why everyone is having issues. I'm manually downgrading.

My is set to "Stable" and I have the 11.0.0 Version overwriting my 10.2.X - so there really might be an issue with it - I just removed the addon for now, as the basic UI has mostly the same features.

**Comment by zaphon** [comment]
Same, there appears to be no setting for "game version" in there. Probably should set the 11.0 version as BETA (since the war within is BETA).

**Comment by R41z0r** [comment]
<img width="878" alt="Bildschirmfoto 2024-06-30 um 20 46 08" src="https://github.com/FabysGames/mythicplustimer/assets/6240199/0481a2eb-3d12-44c2-96be-4b98246453d4">
As you can see on curseforge, there is no Alpha tag on it, it's all for normal retail

**Comment by zaphon** [comment]
Yeah, either the new version needs to be updated to work for both Retail and TWW Beta, or marked as Beta/Alpha so that the updater doesn't pull it.

**Comment by BradCOnGitHub** [comment]
Curseforge doesn't have the ability to only have addons for PTR, only for Retail/Classic flavors. Releasing a 11.x only addon right now will break retail

**Comment by fabysdev** [comment]
> Curseforge doesn't have the ability to only have addons for PTR, only for Retail/Classic flavors. Releasing a 11.x only addon right now will break retail

thank you for reporting that. i flagged the version as Beta

**Comment by Hyphie24** [comment]
Version 6.0.0 percent not adding up correctly, it shows % correctly for mobs being pulled, but when mobs die percent only going up in 1/5, around 20% is full 100%
