### ISSUE TITLE
lua error after finishing a M+ dungeon

### ISSUE THREAD

**Issue by Cassendra** [FabysGames/mythicplustimer#4]
I have this error each time i finish a M+ dungeon :

`Message: [ADDON_ACTION_BLOCKED] AddOn 'MythicPlusTimer' tried to call the protected function 'ObjectiveTrackerFrame:SetParent()'.
Time: Tue Aug  6 18:41:28 2019
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'MythicPlusTimer' tried to call the protected function 'ObjectiveTrackerFrame:SetParent()'.
Interface\AddOns\MythicPlusTimer\main.lua:606: in function `show_default_tracker'
Interface\AddOns\MythicPlusTimer\main.lua:415: in function `callback'
Interface\AddOns\MythicPlusTimer\addon.lua:100: in function <Interface\AddOns\MythicPlusTimer\addon.lua:94>`

**Comment by FabysGames** [comment]
Thanks for the report. Will look at the error

**Comment by FabysGames** [comment]
Hi, I was not able to reproduce it. 
Please try the latest version of the addon.
Thanks
