### ISSUE TITLE
Count% issue in Beta version 6.0.0 in War Within Pre-Patch

### ISSUE THREAD

**Issue by sharpythegoat** [FabysGames/mythicplustimer#41]
The count% shows weird percentages during a m+ run. Nearly at the end of the dungeon I often see a trash count between 13 and 20% , then suddenly marking as complete when the count objective is completed.

**Comment by fabysdev** [comment]
The 11.0 WoW version unfortunately no longer reports the actual count to addons, only the percent number is known.  Reported here: https://github.com/Stanzilla/WoWUIBugs/issues/592

The next version will only show the correct percent values and no longer the actual count - but the pre-patch interface api differs from the beta api so the new version is not available yet, but will be soon.
