### ISSUE TITLE
% bar not working properly

### ISSUE THREAD

**Issue by paessz** [FabysGames/mythicplustimer#42]
Hello Fabys, I saw u att for 11.0.1 but the bar in the % of mobs its not working very well, when we kill 50% of the dungeon it shows 15% in the bar, but the % is correct just the bar that is not showing the right %

Thanks for ur addon I love it, Im just having this problem doing dgs with the addon

**Comment by fabysdev** [comment]
you are right, i missed that spot. should be fixed in the latest version. thank you for reporting
