### ISSUE TITLE
MythicPlusTimer combined with other Addons messes up all frames

### ISSUE THREAD

**Issue by LybrialsGit** [FabysGames/mythicplustimer#8]
Hi,

I have an Addon which overhauls the whole interface like:
- ActionBars
- UnitFrames
- Minimap
- etc.

It works perfectly fine.

As soon as I enable MythicPlusTimer Addon and start a Mythic+ run the whole interface is getting screwed 
up. The unit frames are moved to the very top of the screen and the minimap and actionbars are no longer 
visible.

As soon as I disable MythicPlusTimer and reload the interface everything is back to normal.

It seems like with MythicPlusTimer enabled the UI Scaling changes so that the ActionBars, Minimap and other 
stuff is pushed outside of the visible area of the screen.

**Comment by fabysdev** [comment]
MythicPlusTimer does not use any shared lib or so, also it does not mess with any other frames except the objective tracker "ObjectiveTrackerFrame". What ActionBar / minimap / ... addon do you use?

**Comment by LybrialsGit** [comment]
Hi, first some screenshots so that you know what im talking about.

This is my interface when everything is fine and MythicPlusTimer Addon is **disabled**
![WoWScrnShot_122420_131142](https://user-images.githubusercontent.com/3900682/103088914-ae12d400-45ec-11eb-8aae-8d3e7882071a.jpg)

This is my interface when MythicPlusTimer Addon is **enabled**
![WoWScrnShot_122420_131221](https://user-images.githubusercontent.com/3900682/103088962-d26eb080-45ec-11eb-9343-53aa9418243f.jpg)

I also made screenshots of the errors im getting:

![WoWScrnShot_122420_131219](https://user-images.githubusercontent.com/3900682/103089004-f16d4280-45ec-11eb-9ebc-dd4dfd6bf2af.jpg)
![WoWScrnShot_122420_131216](https://user-images.githubusercontent.com/3900682/103088991-e9150780-45ec-11eb-90f6-7f4aa19eeb4a.jpg)

Im using my own implemenation for minimap, actionbars, questtracker, data bars, data texts, unit frames, etc.

**Comment by fabysdev** [comment]
Feels like your local db is corrupt, have you tried removing the "MythicPlusTimer.lua" files from your WTF\Account\ACCOUNT\SavedVariables directory?
I assume you are using the latest version of the addon.

**Comment by LybrialsGit** [comment]
Yep. Latest version and removed local db.
I know MythicPlusTimer is not doing something with frames. I checked the code. 
But since this is hard to debug (since you need to be in a mythic+ dungeon) I wanted to report this
here in case you guys have an idea.

**Comment by fabysdev** [comment]
Multiple Questions, as i can not get that effect to happen for me ;)

1. Does it also happen if you use the demo mode of the addon outside a dungeon? `/mpt toggle`
2. Does changing the scale in the mythicplustimer option change the ui scale?
3. Does it also happen if you disable the option to hide the default tracker 

Maybe you could send me a list of all addons you use so i can find the one which is incompatible. (Maybe you have your custom ones uploaded somewhere?)

thanks

**Comment by LybrialsGit** [comment]
Number 3 it is!

- My object tracker addon enabled
- MythicPlusTimer enabled
- "Hide default objective tracker" enabled
![WoWScrnShot_122620_114150](https://user-images.githubusercontent.com/3900682/103150003-b2b3c580-476f-11eb-979a-9795d5c8aeae.jpg)

- My object tracker addon enabled
- MythicPlusTimer enabled
- "Hide default objective tracker" disabled
![WoWScrnShot_122620_114153](https://user-images.githubusercontent.com/3900682/103150008-c19a7800-476f-11eb-91f7-d435acb2de14.jpg)

- My object tracker addon disabled
- MythicPlusTimer enabled
- "Hide default objective tracker" enabled
![WoWScrnShot_122620_114248](https://user-images.githubusercontent.com/3900682/103150009-ca8b4980-476f-11eb-8bbe-0b11616a98f2.jpg)

My own object tracker addon has everything replaced, no blizzard default stuff, every frame is self coded.
So I will check how I need to change my code so that it works together with MythicPlusTimer.

Thank you!
